
    name: CI/CD FastAPI

    on:
      push:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Récupérer le code
            uses: actions/checkout@v3

             # Étape de debug des secrets
          - name: Debug secrets (temporaire)
            run: |
              echo "Host: ${{ secrets.SSH_HOST }}"
              echo "User: ${{ secrets.SSH_USER }}"

          - name: Installer Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'

          - name:  Installer les dépendances
            run:
              pip install -r requirements.txt

          - name: Run test
            run:
              pytest

          - name: Créer l'image Docker
            run:
              docker build -t fastapi_image:v0 .

          - name: Deploy via SSH
            uses: appleboy/scp-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              port: 22
              source: "."
              target: "/home/azureuser/fastapi-app"
